var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(g){var k=0;return function(){return k<g.length?{done:!1,value:g[k++]}:{done:!0}}};$jscomp.arrayIterator=function(g){return{next:$jscomp.arrayIteratorImpl(g)}};$jscomp.makeIterator=function(g){var k="undefined"!=typeof Symbol&&Symbol.iterator&&g[Symbol.iterator];return k?k.call(g):$jscomp.arrayIterator(g)};$jscomp.arrayFromIterator=function(g){for(var k,m=[];!(k=g.next()).done;)m.push(k.value);return m};
$jscomp.arrayFromIterable=function(g){return g instanceof Array?g:$jscomp.arrayFromIterator($jscomp.makeIterator(g))};
(function(){function g(k,m,p){function c(b,a){if(!m[b]){if(!k[b]){var d="function"==typeof require&&require;if(!a&&d)return d(b,!0);if(e)return e(b,!0);a=Error("Cannot find module '"+b+"'");throw a.code="MODULE_NOT_FOUND",a;}a=m[b]={exports:{}};k[b][0].call(a.exports,function(h){return c(k[b][1][h]||h)},a,a.exports,g,k,m,p)}return m[b].exports}for(var e="function"==typeof require&&require,f=0;f<p.length;f++)c(p[f]);return c}return g})()({1:[function(g,k,m){var p={init:function(){var c=this,e=document.querySelectorAll(".expandLink"),
f=document.querySelectorAll(".collapseLink"),b=document.querySelectorAll(".accordion-button"),a=document.querySelectorAll(".accordion-collapse"),d=document.querySelectorAll(".mw_ws_accordion_container");e.forEach(function(h){h.addEventListener("click",function(l){l.preventDefault();c.expandAll(e,f,b,a,h.dataset.scope);c.updatePageOpenItems()})});f.forEach(function(h){h.addEventListener("click",function(l){l.preventDefault();c.collapseAll(e,f,b,a,h.dataset.scope);c.updatePageOpenItems()})});d.forEach(function(h){h.addEventListener("shown.bs.collapse",
function(){c.updatePageOpenItems();c.displayOpenedItems()});h.addEventListener("hidden.bs.collapse",function(){c.updatePageOpenItems();c.displayOpenedItems()})});c.displayOpenedItems()},expandAll:function(c,e,f,b,a){"all"!==a&&(f=document.querySelectorAll(".button_"+a),b=document.querySelectorAll(".body_"+a),c=document.querySelectorAll(".expand_"+a),e=document.querySelectorAll(".collapse_"+a));f.forEach(function(d){d.classList.remove("collapsed")});b.forEach(function(d){d.classList.add("show")});
c.forEach(function(d){d.style.display="none"});e.forEach(function(d){d.style.display="block"})},collapseAll:function(c,e,f,b,a){"all"!==a&&(f=document.querySelectorAll(".button_"+a),b=document.querySelectorAll(".body_"+a),c=document.querySelectorAll(".expand_"+a),e=document.querySelectorAll(".collapse_"+a));f.forEach(function(d){d.classList.add("collapsed")});b.forEach(function(d){d.classList.remove("show")});c.forEach(function(d){d.style.display="block"});e.forEach(function(d){d.style.display="none"})},
getSessionData:function(){return sessionStorage.getItem("expand")},storeSessionData:function(c){sessionStorage.expand=JSON.stringify(c)},getOpenItems:function(c,e){var f=this.getSessionData(),b=this.getPageOpenItems(),a={url:c,query:e,open:this.getQueryStringExpand(e)},d=a.open,h=!1;a.open.push.apply(a.open,$jscomp.arrayFromIterable(b));var l={page:[a]};f?(l=JSON.parse(f),l.page.forEach(function(n){n.url===c&&n.query===e&&(h=!0,n.open.push.apply(n.open,$jscomp.arrayFromIterable(a.open)),n.open=[].concat($jscomp.arrayFromIterable(new Set(n.open))),
d=[].concat($jscomp.arrayFromIterable(new Set(n.open))))}),h&&0<b.length&&this.storeSessionData(l),h||(l.page.push(a),this.storeSessionData(l))):this.storeSessionData(l);return d},getQueryStringExpand:function(c){c=new URLSearchParams(c);var e=[];if(c.has("expand")){var f=c.get("expand").split(",");document.querySelectorAll(".accordion-collapse").forEach(function(b,a){f.includes(b.id)&&e.push(a)})}return e},getPageOpenItems:function(){var c=[];document.querySelectorAll(".accordion-collapse").forEach(function(e,
f){e.classList.contains("show")&&c.push(f)});return c},updatePageOpenItems:function(){var c=this,e=window.location.pathname,f=window.location.search.slice(1),b=c.getSessionData();b=JSON.parse(b);b.page.forEach(function(a){a.url===e&&a.query===f&&(a.open=c.getPageOpenItems())});c.storeSessionData(b)},displayOpenedItems:function(){var c=window.location.pathname,e=window.location.search.slice(1),f=this.getOpenItems(c,e);document.querySelectorAll(".accordion-button").forEach(function(b,a){f.includes(a)&&
b.classList.remove("collapsed")});document.querySelectorAll(".accordion-collapse").forEach(function(b,a){f.includes(a)&&b.classList.add("show")});document.querySelectorAll(".mw_ws_accordion_container").forEach(function(b){if(b.querySelector(".accordion_links")){var a=0,d=0;b.querySelectorAll(".accordion-collapse").forEach(function(l){a++;l.classList.contains("show")&&d++});var h=b.querySelector(".expandLink");b=b.querySelector(".collapseLink");a===d?(h.style.display="none",b.style.display="block"):
0===d&&(h.style.display="block",b.style.display="none")}})}};k.exports=p;document.addEventListener("DOMContentLoaded",function(){p.init()})},{}]},{},[1]);