var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(h){var f=0;return function(){return f<h.length?{done:!1,value:h[f++]}:{done:!0}}};$jscomp.arrayIterator=function(h){return{next:$jscomp.arrayIteratorImpl(h)}};$jscomp.makeIterator=function(h){var f="undefined"!=typeof Symbol&&Symbol.iterator&&h[Symbol.iterator];return f?f.call(h):$jscomp.arrayIterator(h)};$jscomp.arrayFromIterator=function(h){for(var f,k=[];!(f=h.next()).done;)k.push(f.value);return k};
$jscomp.arrayFromIterable=function(h){return h instanceof Array?h:$jscomp.arrayFromIterator($jscomp.makeIterator(h))};var mwaEmail,mwaCountry,mwaFirstName,mwaLastName,mwaReferenceId,isLoggedIn,profileDataLoadAttempted,primaryDomain=!0,domainInterval,iframeLoaded=!1,MWEmbeddedStatus;window.MathWorks=window.MathWorks||{};"use strict";void 0===MWEmbeddedStatus&&(MWEmbeddedStatus={});String.prototype.endsWith=function(h){var f=this.length-h.length;return 0<=f&&this.lastIndexOf(h)===f};
MWEmbeddedStatus=function(){var h=function(f,k){this.config=Object.assign({},f||{})};h.initialize=function(f,k){f=new h(f,k);try{return h.instance=f}catch(a){}};h.checkStatus=function(){if(this.instance.config.skipCheck)window.requestedDomain&&-1<window.location.hostname.indexOf("mathworks.cn")&&h.redirectToSSO(this.instance.config.embeddedEndpoint+h.ssoStatusEndpoint());else{var f=h.findCookie("mwa_SID");if(null===f)h.redirectToSSO(this.instance.config.embeddedEndpoint+h.ssoStatusEndpoint());else if('""'!==
f&&""!==f){var k=h.findCookie(h.getMWACookie());k&&-1!==k.indexOf(f)||h.redirectToSSO(this.instance.config.embeddedEndpoint+h.ssoStatusEndpoint())}}};h.redirectToSSO=function(f){window.location.replace(f)};h.ssoStatusEndpoint=function(){return"v2/status/redirect?origin\x3d"+encodeURIComponent("https://"+window.location.hostname)+"\x26forward\x3d"+encodeURIComponent(location.href)};h.getMWACookie=function(){var f=this.instance.config.embeddedEndpoint,k=f.indexOf("login-"),a="mwa";-1!==k&&(a=a+"_"+
f.substring(k+6,f.indexOf(".")));return a.endsWith("dev")||a.endsWith("test")?a+"1":a};h.findCookie=function(f){f+="\x3d";for(var k=decodeURIComponent(document.cookie).split(";"),a=0;a<k.length;a++){for(var b=k[a];" "===b.charAt(0);)b=b.substring(1);if(0===b.indexOf(f))return b.substring(f.length,b.length)}};h.logout=function(){document.cookie="mwa_SID\x3d; domain\x3d"+window.location.hostname+";path\x3d/; expires\x3dThu, 18 Dec 2013 12:00:00 UTC"};return h}();
(function(){function h(f,k,a){function b(c,g){if(!k[c]){if(!f[c]){var m="function"==typeof require&&require;if(!g&&m)return m(c,!0);if(e)return e(c,!0);g=Error("Cannot find module '"+c+"'");throw g.code="MODULE_NOT_FOUND",g;}g=k[c]={exports:{}};f[c][0].call(g.exports,function(l){return b(f[c][1][l]||l)},g,g.exports,h,f,k,a)}return k[c].exports}for(var e="function"==typeof require&&require,d=0;d<a.length;d++)b(a[d]);return b}return h})()({1:[function(h,f,k){f.exports={isRewritten:function(a){return"content"!==
a[3]},isExemptContext:function(a){var b=this.getDomain(a),e=this.isMarketingDomain(b);return this.isApplicationDomain(b)||!b.endsWith(".mathworks.com")&&!b.endsWith(".mathworks.cn")||this.isMatlabAcademyDomain(b)&&!this.isSameWindow()?!0:"/services/training/schedule_enroll.html /company/aboutus/directions.html /programs/nrd /programs/usrp /company/events/seminars/intl_reg_form.html /googlee8a9c0de75ed5e40.html /mwaccount/profiles/identity/ /mwaccount/profiles/incomplete /mwaccount/profiles/reverify /mwaccount/profiles/reverify/email /mwaccount/profiles/verify /mwaccount/profiles/verify/existing /login /login/association/tah/existing /login/verification/tah/new /login/verification/tah/reverify".split(" ").some(function(d){return e&&
a.includes(d)})},getDomain:function(a){a=a.split("/");return this.isRewritten(a)?a[2]:a[5]},getSubdomain:function(a){var b=/^([a-z0-9]{2,})\./.exec(a);if(b)return b[1];if(b=/^(aem-)?([a-z0-9]{2,3})-/.exec(a))return b[2];if(b=/^([a-z0-9]{2,})$/.exec(a))return b[1];if(b=/(^(mathworks--)(((integ|dev|test)[1-3])|perf|stage))/.exec(a))return"www-"+b[3];if(b=/(^(mathworks--)(mangesha|uat))/.exec(a))return"www";if(b=/^([a-z0-9]+)-(((integ|dev|test)[1-3])|perf|stage)/.exec(a))return b[1];throw"cannot determine subdomain for domain "+
a;},getLang:function(a){a=a.split("/");return this.isRewritten(a)?a[3]&&a[3].match(/^[a-z][a-z]$/)?a[3]:"ch"===this.getSubdomain(a[2])?"en":"ww2"===this.getSubdomain(a[2])?"zh":"":a[6].substr(0,2)},rewriteUrl:function(a,b,e){a=a.split("/");"content"===a[3]?(a[5]=b,a[6]=e):(a[2]=b,a[3]&&a[3].match(/^[a-z][a-z]$/)?"en"===e&&b.startsWith("ch")||"zh"===e&&b.endsWith("mathworks.cn")?a.splice(3,1):a[3]=e:!e||"en"===e&&b.startsWith("ch")||"zh"===e&&b.endsWith("mathworks.cn")||a.splice(3,0,e));return a.join("/")},
setCookie:function(a,b){var e="mathworks.com";location.host.endsWith("mathworks.cn")&&(e="mathworks.cn");var d=this.getSubdomain(a);a.endsWith("mathworks.cn")&&(d="cn");"www"===d&&(d="us");"cn"!==d&&"ch"!==d&&(b="");a=this.getCookieNames(a);var c=new Date;c.setFullYear(c.getFullYear()+68);document.cookie=[a.mwaPrefsCookieName,"\x3d",encodeURIComponent(JSON.stringify({domain:d,lang:b,v:2})),"; expires\x3d",c.toUTCString(),"; path\x3d/; domain\x3d",e,"; sameSite\x3dLax; secure"].join("")},logoutMWA:function(a){var b=
"mathworks.com";location.host.endsWith("mathworks.cn")&&(b="mathworks.cn");a=this.getCookieNames(a);document.cookie=a.mwaLoginCookieName+"\x3d;expires\x3dThu, 01 Jan 1970 00:00:01 GMT;path\x3d/;domain\x3d"+b+";"},getSubdomainSuffix:function(a){var b;a=a.split(".")[0].split("-");1<a.length&&(b=a[a.length-1]);return b},getCookieNames:function(a){var b="mwa",e="mwa_prefs";if(a=this.getSubdomainSuffix(a))b=b+"_"+a,e=e+"_"+a;return{mwaLoginCookieName:b,mwaPrefsCookieName:e}},switchDomain:function(a,b,
e){var d=location.pathname;d.match(/^\/[a-z]{2}\//)?d=d.substring(3):d.match(/^\/[a-z]{2}\.html/)&&(d="/");b=this.getValidLang(this.getSubdomain(a),b);var c="//"+a;!b||this.isDefaultLang(this.getSubdomain(a),b)||document.body.classList.contains("templateservice")||(c+="/"+b);c+=d+location.search;c=c.replace(/requestedDomain=[a-z]?[a-z]?&?/,"");c=c.replace(/&$/,"");c=c.replace(/\?$/,"");b="requestedDomain\x3d"+b;c=-1<c.indexOf("?")?c+"\x26"+b:c+"?"+b;e&&"undefined"!==typeof Visitor&&this.getDomainExtension(window.location.host)!==
this.getDomainExtension(a)&&(c=Visitor.getInstance("B1441C8B533095C00A490D4D@AdobeOrg",{trackingServer:"metrics.mathworks.com",trackingServerSecure:"smetrics.mathworks.com",marketingCloudServer:"metrics.mathworks.com",marketingCloudServerSecure:"smetrics.mathworks.com"}).appendVisitorIDsTo(c).replace(/MCAID%3D.*%7CMCORGID/,"MCAID%3D%7CMCORGID"));location.hash&&(c+=location.hash);window.location=c},getDomainExtension:function(a){a=-1===a.indexOf("https://")?"https://"+a:a;a=(new URL(a)).host.split(".");
return a[a.length-1]},getPrefCookie:function(a){a=this.getCookieNames(a);a=new RegExp("(?:(?:^|.*;\\s*)"+a.mwaPrefsCookieName+"\\s*\\\x3d\\s*([^;]*).*$)|^.*$");return document.cookie&&(a=document.cookie.replace(a,"$1"))?JSON.parse(decodeURIComponent(a)):""},getPrefDomain:function(a){var b=this.getPrefCookie(a);if(b){var e=b.domain;"us"===e&&(e="www");a=this.getSubdomainSuffix(a);"cn"!==e?(-1==="la nl se de es fr uk it ch au in jp kr".split(" ").indexOf(e)&&(e="www"),a&&(e=e+"-"+a),e+=".mathworks.com"):
(e="ww2",a&&(e=e+"-"+a),e+=".mathworks.cn")}return e},getPrefLang:function(a){a=this.getPrefCookie(a);return this.getValidLang(a.domain,a.lang)},getCookieVersion:function(a){return this.getPrefCookie(a).v},getValidLang:function(a,b){return(a={ch:["en","de","fr"],cn:["zh","en"],ww2:["zh","en"]}[a])?0<=a.indexOf(b)?b:a[0]:""},isDefaultLang:function(a,b){return(a={ch:"en",cn:"zh",ww2:"zh"}[a])?a===b:b?!1:!0},isApplicationDomain:function(a){return!!/^aem-(auth|pub)-([^.]+)(\.mathworks\.com)?(:\d{4})?$/.exec(a)},
isMarketingDomain:function(a){return!!/^((au|ch|de|es|fr|in|it|jp|kr|la|nl|se|uk|www)(-(((dev|test|integ)[123])|perf|stage|local))?\.mathworks\.com|ww2(-(((dev|test|integ)[123])|perf|stage|local))?\.mathworks\.cn)/.exec(a)},isMatlabAcademyDomain:function(a){return!!/^matlabacademy(-(((dev|test|integ)[123])|perf|stage|local))?\.mathworks\.com/.exec(a)},isSameWindow:function(){return window.self===window.top}}},{}],2:[function(h,f,k){f.exports={getCookie:function(a){var b=document.cookie.split(";");
b=$jscomp.makeIterator(b);for(var e=b.next();!e.done;e=b.next())if(e=e.value.replace(/^\s+|\s+$/g,""),e.startsWith(a+"\x3d"))return decodeURIComponent(e.substring(a.length+1,e.length));return null}}},{}],3:[function(h,f,k){var a=h("../../../components/domainRedirect/utils.js"),b=h("./utils.js"),e=h("../../../helpers/cookie.js");h={init:function(){var d=window.location.href,c=a.getDomain(d),g=this.getBaseUrl("https://"+window.location.hostname),m="true"===$("body").attr("data-is-homepage"),l=b.getMWACookieNames(c);
c=l.mwaDeprecatedAccountLoginCookieName;var q=l.mwaLoginCookieName;l=l.mwaLoginProfileCookieName;this.checkMWLoginCookie(q);this.attemptShowLogin(q,l,c,g,m,d,0);this.attemptSSOLogin();window.addEventListener("updateLoginUrl",function(){var r;null==(r=document.querySelectorAll(isLoggedIn?".mwa-logout":".mwa-nav_login"))||r.forEach(function(n){var p=n.getAttribute("href");p&&"#"!==p.trim()&&(p=new URL(p),p.searchParams.set("uri",window.location.href),n.setAttribute("href",p.toString()))})})},checkMWLoginCookie:function(d){isLoggedIn=
!!e.getCookie(d)},redirectUrl:function(d){return window.customGlobalNavRedirectUrl||d},showLoggedOut:function(d,c,g){var m=this;isLoggedIn=!1;profileDataLoadAttempted=!0;var l=document.body.dataset.cid;$(".not-logged-in").show();if(l){var q=a.getSubdomainSuffix(d),r="https://login.mathworks.com/";q&&(r="https://login-"+q+".mathworks.com/");var n;null==(n=document.querySelectorAll(".mwa-nav_login"))||n.forEach(function(p){p.setAttribute("href",r+"embedded-login/signin.html?cid\x3d"+l+"\x26wid\x3dgnav"+
(c?"":"\x26uri\x3d"+encodeURIComponent(m.redirectUrl(g))))})}else null==(q=document.querySelectorAll(".mwa-nav_login"))||q.forEach(function(p){p.setAttribute("href",d+"/login"+(c?"":"?uri\x3d"+encodeURIComponent(m.redirectUrl(g))))});$(".headernav_login").show()},populateContactForm:function(d,c,g,m){if($('input[name\x3d"E_mail"]').length){var l=$('input[name\x3d"E_mail"]');l.val(d);l.prop("readonly",!0)}$('input[name\x3d"First_Name"]').length&&(d=$('input[name\x3d"First_Name"]'),d.val(c),d.prop("readonly",
!0));$('input[name\x3d"Last_Name"]').length&&(c=$('input[name\x3d"Last_Name"]'),c.val(g),c.prop("readonly",!0));$('select[name\x3d"Country"]').length&&(g=$('select[name\x3d"Country"]'),g.val()||g.val(m).change())},hideDomainContent:function(d){if("undefined"!==typeof filterDomains&&isLoggedIn&&filterDomains)if(d){var c=filterDomains.split(",");d=d.split("@");-1<$.inArray("@"+d[1],c)?($(".domain-specific").show(),$(".not-domain-specific").hide()):($(".domain-specific").hide(),$(".not-domain-specific").show())}else $(".domain-specific").hide(),
$(".not-domain-specific").show()},showLoggedIn:function(d,c,g){var m=this;isLoggedIn=!0;var l=new CustomEvent("mwa-auth:user-logged-in",{detail:{loginDisplayed:!0}});window.dispatchEvent(l);l=c+"/etc.clientlibs/mathworks/clientlibs/customer-ui/templates/common/resources/images/ico-header-account-active.20250820203440005.svg";var q="",r="";d.profile&&(d.profile.profilePicture&&(q=c+"/matlabcentral/profiles/"+d.profile.profilePicture),d.profile.loginDisplayName&&(r=d.profile.loginDisplayName));$(".logged-in").show();
$(".mwa-name").text(r);d=document.body.classList.contains("-has_usernav")?"user_nav_":"gn_";$(".mwa-account").attr("href",c+"/mwaccount/?s_tid\x3d"+d+"myac");$(".mwa-link-license").attr("href",c+"/licensecenter/licenses/add?s_tid\x3d"+d+"aslc");$(".mwa-community-profile").attr("href",c+"/matlabcentral/profile/authors/my_profile?s_tid\x3d"+d+"comm");$(".mwa-logout").attr("href",c+"/login/logout?uri\x3d"+encodeURIComponent(m.redirectUrl(g)));$(".mwa_image_drop_down").attr("style","background-image:url("+
q+"), url("+l+")").attr("alt",r);$(".mobile_account_image").attr("style","background-image:url("+q+"), url("+l+")").attr("alt",r);$(".mobile_account_name").append(r);$(".headernav_logout").show();$.get({url:c+"/bin/mathworks/profile.json",xhrFields:{withCredentials:!0},success:function(n){mwaEmail=n.email;mwaCountry=n.country;mwaFirstName=n.firstName;mwaLastName=n.lastName;mwaReferenceId=n.referenceId;m.hideDomainContent(mwaEmail);m.populateContactForm(mwaEmail,mwaFirstName,mwaLastName,mwaCountry);
n=new CustomEvent("mwa-auth:user-profile-data",{detail:{email:mwaEmail,country:mwaCountry,firstName:mwaFirstName,lastName:mwaLastName,referenceId:mwaReferenceId}});window.dispatchEvent(n)}}).always(function(){profileDataLoadAttempted=!0})},refreshProfileCookie:function(d,c,g,m,l,q,r){var n=this;$.get({url:m+"/login/cookies/refresh?uri\x3d"+encodeURIComponent("/login"),xhrFields:{withCredentials:!0}},function(){n.attemptShowLogin(d,c,g,m,l,q,r)}).fail(function(p){403===p.status?window.location=p.responseJSON.redirectUrl:
n.attemptShowLogin(d,c,g,m,l,q,r)})},attemptShowLogin:function(d,c,g,m,l,q,r){var n=e.getCookie(d),p=e.getCookie(c);if(5<r++)this.showLoggedOut(m,l,q);else if(n){var t=JSON.parse(n);n="";null!==t&&(null==t?0:t.id)&&(n=t.id);p?(p=JSON.parse(p),t="",null!==p&&(null==p?0:p.id)&&(t=p.id),n&&t&&n===t?this.showLoggedIn(p,m,q):this.refreshProfileCookie(d,c,g,m,l,q,r)):this.refreshProfileCookie(d,c,g,m,l,q,r)}else e.getCookie(g)?this.refreshProfileCookie(d,c,g,m,l,q,r):this.showLoggedOut(m,l,q)},attemptSSOLogin:function(){var d=
"https://login.mathworks.com/embedded-login/",c;-1===window.location.hostname.indexOf("www.mathworks")&&-1===window.location.hostname.indexOf("ww2.mathworks")&&0<window.location.hostname.indexOf("-")&&(null==(c=window.location.hostname.split(".")[0])?0:c.split("-")[1].match(/^(dev|test|stage|perf|integ)[0-9]?$/))&&(d="https://login-"+window.location.hostname.split(".")[0].split("-")[1]+".mathworks.com/embedded-login/");var g;MWEmbeddedStatus.initialize({embeddedEndpoint:d,skipCheck:-1<window.location.hostname.indexOf("mathworks.com")||
-1<window.location.hostname.indexOf("matlabexpo.com")||-1<window.location.hostname.indexOf("mathworks.cn")&&(window.requestedDomain||-1<window.location.hostname.indexOf("local"))||0<window.location.hostname.indexOf("-")&&!(null==(g=window.location.hostname.split(".")[0])?0:g.split("-")[1].match(/^(local|dev|test|stage|perf|integ)[0-9]?$/))});MWEmbeddedStatus.checkStatus()},getBaseUrl:function(d){/^https:\/\/((au|ch|de|es|fr|in|it|jp|kr|la|nl|se|uk|www)(-(((dev|test|integ)[123])|perf|stage|local))?\.mathworks\.com|ww2(-(((dev|test|integ)[123])|perf|stage|local))?\.mathworks\.cn)/.exec(d)||
(d=d.split("//")[1].split(".")[0].split("-"),d=(d=void 0!==d[1]?d[1]:"")?"https://www-"+d+".mathworks.com":"https://www.mathworks.com");return d}};f.exports=h;h.init()},{"../../../components/domainRedirect/utils.js":1,"../../../helpers/cookie.js":2,"./utils.js":4}],4:[function(h,f,k){f.exports={getMWACookieNames:function(a){var b="mwa",e="mwa_session",d="mwa_profile";a=a.split(".")[0].split("-");1<a.length&&(a=a[a.length-1],b=b+"_"+a,e=e+"_"+a,d=d+"_"+a);return{mwaLoginCookieName:b,mwaLoginSessionCookieName:e,
mwaLoginProfileCookieName:d,mwaDeprecatedAccountLoginCookieName:"MW_AL",mwaEmailAddressCookieName:"mwa_dc"}}}},{}]},{},[3]);
(function(){function h(f,k,a){function b(c,g){if(!k[c]){if(!f[c]){var m="function"==typeof require&&require;if(!g&&m)return m(c,!0);if(e)return e(c,!0);g=Error("Cannot find module '"+c+"'");throw g.code="MODULE_NOT_FOUND",g;}g=k[c]={exports:{}};f[c][0].call(g.exports,function(l){return b(f[c][1][l]||l)},g,g.exports,h,f,k,a)}return k[c].exports}for(var e="function"==typeof require&&require,d=0;d<a.length;d++)b(a[d]);return b}return h})()({1:[function(h,f,k){h={init:function(){this.computeDataComponentAttributes()},
computeDataComponentAttributes:function(){var a=this;$("[data-link]").each(function(){$(this).attr("data-component",a.findResource(this,".containsPriorityResourceName")||a.findResource(this,".containsResourceName")||"link")});$(".fat_footer_container").find('[data-component\x3d"text"]').attr("data-component","footer");var b=document.querySelector("#extended_footer");null!==b&&b.querySelectorAll('[data-component\x3d"text"]').forEach(function(e){e.setAttribute("data-component","footer")})},findResource:function(a,
b){if(a=$(a).closest(b).attr("class"))for(a=a.split(" "),b=0;b<a.length;b++){var e=a[b];if(e.startsWith("resourceClass-")){var d=e.substring(14);break}}return d}};f.exports=h;h.init()},{}]},{},[1]);
(function(){function h(f,k,a){function b(c,g){if(!k[c]){if(!f[c]){var m="function"==typeof require&&require;if(!g&&m)return m(c,!0);if(e)return e(c,!0);g=Error("Cannot find module '"+c+"'");throw g.code="MODULE_NOT_FOUND",g;}g=k[c]={exports:{}};f[c][0].call(g.exports,function(l){return b(f[c][1][l]||l)},g,g.exports,h,f,k,a)}return k[c].exports}for(var e="function"==typeof require&&require,d=0;d<a.length;d++)b(a[d]);return b}return h})()({1:[function(h,f,k){h={init:function(){this.initializeDigitalData()},
initializeDigitalData:function(){"undefined"!==typeof digitalData&&(digitalData.hasOwnProperty("user")||(digitalData.user=[]),0===digitalData.user.length&&digitalData.user.push({}),digitalData.user[0].hasOwnProperty("segment")||(digitalData.user[0].segment={}))}};f.exports=h;h.init()},{}]},{},[1]);
(function(){function h(f,k,a){function b(c,g){if(!k[c]){if(!f[c]){var m="function"==typeof require&&require;if(!g&&m)return m(c,!0);if(e)return e(c,!0);g=Error("Cannot find module '"+c+"'");throw g.code="MODULE_NOT_FOUND",g;}g=k[c]={exports:{}};f[c][0].call(g.exports,function(l){return b(f[c][1][l]||l)},g,g.exports,h,f,k,a)}return k[c].exports}for(var e="function"==typeof require&&require,d=0;d<a.length;d++)b(a[d]);return b}return h})()({1:[function(h,f,k){var a={init:function(){var b=this;b.mobileNav();
b.ctas();b.modals();["resize","orientationchange"].forEach(function(e){window.addEventListener(e,function(){b.mobileNav();b.ctas()})})},mobileNav:function(){var b=document.getElementById("main_navigation");if(b){var e=document.getElementById("topnav_mwa"),d=document.getElementById("headernav_matrix");992>window.innerWidth?(d&&d.insertAdjacentElement("afterend",b),null==e||e.parentElement.insertAdjacentElement("afterbegin",e)):(d&&d.insertAdjacentElement("beforebegin",b),null==e||e.parentElement.insertAdjacentElement("beforeend",
e))}},ctas:function(){var b=document.querySelector(".resourceClass-calltoactionheader");b&&(992>window.innerWidth?document.getElementById("main").insertAdjacentElement("afterend",b):document.getElementById("cta_container").append(b))},modals:function(){if(!document.body.classList.contains("templateservice")){var b=document.querySelectorAll("body main div[id^\x3d'modal-']"),e=new Set,d=function(c){return c&&"div"===c.tagName.toLowerCase()&&c.classList.contains("modalParsys")};b.forEach(function(c){var g=
c.parentElement,m=g.parentElement;d(g)||d(m)||(e.has(c.id)?c.remove():(e.add(c.id),document.body.appendChild(c)))})}}};f.exports=a;document.addEventListener("DOMContentLoaded",function(){a.init()})},{}]},{},[1]);
(function(){function h(f,k,a){function b(c,g){if(!k[c]){if(!f[c]){var m="function"==typeof require&&require;if(!g&&m)return m(c,!0);if(e)return e(c,!0);g=Error("Cannot find module '"+c+"'");throw g.code="MODULE_NOT_FOUND",g;}g=k[c]={exports:{}};f[c][0].call(g.exports,function(l){return b(f[c][1][l]||l)},g,g.exports,h,f,k,a)}return k[c].exports}for(var e="function"==typeof require&&require,d=0;d<a.length;d++)b(a[d]);return b}return h})()({1:[function(h,f,k){var a={init:function(){[].concat($jscomp.arrayFromIterable(document.querySelectorAll('[data-bs-toggle\x3d"tooltip"]'))).map(function(b){return new bootstrap.Tooltip(b)})}};
f.exports=a;document.addEventListener("DOMContentLoaded",function(){a.init()})},{}]},{},[1]);
(function(){function h(f,k,a){function b(c,g){if(!k[c]){if(!f[c]){var m="function"==typeof require&&require;if(!g&&m)return m(c,!0);if(e)return e(c,!0);g=Error("Cannot find module '"+c+"'");throw g.code="MODULE_NOT_FOUND",g;}g=k[c]={exports:{}};f[c][0].call(g.exports,function(l){return b(f[c][1][l]||l)},g,g.exports,h,f,k,a)}return k[c].exports}for(var e="function"==typeof require&&require,d=0;d<a.length;d++)b(a[d]);return b}return h})()({1:[function(h,f,k){var a={init:function(){var b=document.querySelector("#sticky_container");
b&&window.addEventListener("scroll",function(){var e=window.scrollY||window.pageYOffset;0>=b.getBoundingClientRect().top&&0<e?b.classList.add("-locked"):b.classList.remove("-locked")})}};f.exports=a;document.addEventListener("DOMContentLoaded",function(){a.init()})},{}]},{},[1]);