(function(){function p(h,k,f){function a(c,e){if(!k[c]){if(!h[c]){var l="function"==typeof require&&require;if(!e&&l)return l(c,!0);if(b)return b(c,!0);e=Error("Cannot find module '"+c+"'");throw e.code="MODULE_NOT_FOUND",e;}e=k[c]={exports:{}};h[c][0].call(e.exports,function(m){return a(h[c][1][m]||m)},e,e.exports,p,h,k,f)}return k[c].exports}for(var b="function"==typeof require&&require,d=0;d<f.length;d++)a(f[d]);return a}return p})()({1:[function(p,h,k){var f={preloadInit:function(){var a=document.getElementById("template_offcanvas");
f.isMobileWidth()||!f.isTocOpen()||a.classList.contains("offcanvas_fixed")||(document.getElementById("template_offcanvas").classList.add("no_animate"),document.getElementById("offcanvas_menu").classList.add("show"),document.getElementById("offcanvas_actuator").classList.add("collapsed"),document.getElementById("offcanvas_actuator").setAttribute("aria-expanded","true"),document.getElementById("offcanvas_menu_content").removeAttribute("aria-hidden"))},init:function(){var a=this;a.updateWidthsAndHeights();
a.relocateNav();a.toggleNavListWrapper();document.body.classList.contains("-has_corporatenav")||document.body.classList.contains("-has_usernav")||["shown.bs.collapse","hidden.bs.collapse"].forEach(function(b){document.getElementById("main_navigation").addEventListener(b,function(){a.updateWidthsAndHeights()})});document.addEventListener("scroll",function(){a.updateWidthsAndHeights()});["resize","orientationchange"].forEach(function(b){window.addEventListener(b,function(){a.updateWidthsAndHeights();
a.relocateNav()})});document.getElementById("offcanvas_actuator").addEventListener("click",function(b){b=b.currentTarget.getAttribute("aria-expanded");var d=document.getElementById("template_offcanvas"),c=document.getElementById("offcanvas_menu_content");a.setTOCSession("true"===b);d.classList.remove("no_animate");"true"===b?(c.removeAttribute("aria-hidden"),c.querySelectorAll("a").forEach(function(e){e.removeAttribute("aria-hidden");e.removeAttribute("tabindex")})):(c.setAttribute("aria-hidden",
"true"),c.querySelectorAll("a").forEach(function(e){e.setAttribute("aria-hidden","true");e.setAttribute("tabindex","-1")}))});document.getElementById("offcanvas_focus_actuator").addEventListener("focus",function(){var b=document.getElementById("offcanvas_actuator").getAttribute("aria-expanded"),d=document.getElementById("offcanvas_menu"),c=document.getElementById("offcanvas_menu_content");"true"===b&&(new bootstrap.Collapse(d,{toggle:!0}),c.setAttribute("aria-hidden","true"),c.querySelectorAll("a").forEach(function(e){e.setAttribute("aria-hidden",
"true");e.setAttribute("tabindex","-1")}))})},toggleNavListWrapper:function(){var a=document.getElementById("offcanvas_actuator").getAttribute("aria-expanded"),b=document.getElementById("offcanvas_menu_content");"true"===a||"offcanvas_fixed_menu_container"===b.parentElement.id?setTimeout(function(){b.removeAttribute("aria-hidden");b.querySelectorAll("a").forEach(function(d){d.removeAttribute("aria-hidden");d.removeAttribute("tabindex")})},700):setTimeout(function(){b.setAttribute("aria-hidden","true");
b.querySelectorAll("a").forEach(function(d){d.setAttribute("aria-hidden","true");d.setAttribute("tabindex","-1")})},700)},updateWidthsAndHeights:function(){var a,b=null==(a=document.getElementsByTagName("header"))?void 0:a[0],d=document.getElementById("sticky_container");a=document.getElementById("offcanvas_menu");var c=document.getElementById("template_offcanvas"),e=document.getElementById("offcanvas_body"),l=window.innerWidth,m=l;b&&(m-=getComputedStyle(b).getPropertyValue("width").slice(0,-2));
var n=window.innerHeight;b=b?b.offsetHeight:0;var g=d?d.offsetHeight:0;d=n-b-g;var q=document.body.classList.contains("-has_usernav");q&&(d=n-g);n-=g;g=Math.max(window.scrollY,document.documentElement.scrollTop,document.body.scrollTop);var r=d+g;0===g?(c.classList.remove("locked"),a.style.height=d+"px"):g>b||q?(c.classList.add("locked"),a.style.height=n+"px"):(c.classList.remove("locked"),a.style.height=r+"px");e.style.width=768>l?"calc(100vw - "+(m+37)+"px)":"auto"},relocateNav:function(){var a=
document.getElementById("template_offcanvas"),b=document.getElementById("offcanvas_menu_content");a.classList.contains("offcanvas_fixed")&&(992>window.innerWidth&&"offcanvas_fixed_menu_container"===b.parentElement.id?(document.getElementById("offcanvas_actuator").insertAdjacentElement("afterend",b),f.toggleNavListWrapper()):992<=window.innerWidth&&"offcanvas_fixed_menu_container"!==b.parentElement.id&&(document.getElementById("offcanvas_fixed_menu_container").insertAdjacentElement("beforeend",b),
f.toggleNavListWrapper()))},isTocOpen:function(){var a=sessionStorage.getItem(this.getSessionName());return null===a||"true"===a},setTOCSession:function(a){sessionStorage.setItem(this.getSessionName(),a)},getSessionName:function(){var a=document.getElementById("offcanvas_menu").dataset.offcanvasId;return"MW_toc_visible::"+(a?a:location.pathname)},isMobileWidth:function(){return 768>document.body.clientWidth}};h.exports=f;f.preloadInit();document.addEventListener("DOMContentLoaded",function(){f.init()})},
{}]},{},[1]);