this.Mathworks=this.Mathworks||{};this.Mathworks.templates=this.Mathworks.templates||{};
this.Mathworks.templates.searchbasictypeahead=Handlebars.template({1:function(e,c,k,f,a){var g;f=e.lookupProperty||function(h,d){if(Object.prototype.hasOwnProperty.call(h,d))return h[d]};return'\t\t\x3cul class\x3d"suggestionarea dropdown-menu d-block" id\x3d"search_suggestions" role\x3d"listbox"\x3e\n'+(null!=(g=f(k,"each").call(null!=c?c:e.nullContext||{},null!=c?f(c,"suggestions"):c,{name:"each",hash:{},fn:e.program(2,a,0),inverse:e.noop,data:a,loc:{start:{line:4,column:3},end:{line:10,column:12}}}))?
g:"")+"\t\t\x3c/ul\x3e\n"},2:function(e,c,k,f,a){var g,h;f=null!=c?c:e.nullContext||{};var d=e.hooks.helperMissing,b=e.escapeExpression,l=e.lambda;e=e.lookupProperty||function(n,m){if(Object.prototype.hasOwnProperty.call(n,m))return n[m]};return'\t\t\t\t\x3cli class\x3d"suggestion" id\x3d"suggestion_'+b((h=null!=(h=e(k,"index")||a&&e(a,"index"))?h:d,"function"===typeof h?h.call(f,{name:"index",hash:{},data:a,loc:{start:{line:5,column:42},end:{line:5,column:52}}}):h))+'"\x3e\n\t\t\t\t\t\x3ca class\x3d"suggestion_item dropdown-item" href\x3d"#" role\x3d"option" data-value\x3d"'+
b(l(c,c))+'"\x3e\n\t\t\t\t\t\t\x3cspan class\x3d"suggestion_highlight"\x3e'+b(l((g=a&&e(a,"root"))&&e(g,"qvalue"),c))+"\x3c/span\x3e"+b((e(k,"getSuggestionHighlights")||c&&e(c,"getSuggestionHighlights")||d).call(f,(g=a&&e(a,"root"))&&e(g,"qvalue"),c,{name:"getSuggestionHighlights",hash:{},data:a,loc:{start:{line:7,column:64},end:{line:7,column:109}}}))+"\n\t\t\t\t\t\x3c/a\x3e\n\t\t\t\t\x3c/li\x3e\n"},compiler:[8,"\x3e\x3d 4.3.0"],main:function(e,c,k,f,a){var g;f=e.lookupProperty||function(h,d){if(Object.prototype.hasOwnProperty.call(h,
d))return h[d]};return'\x3cdiv class\x3d"typeahead_container typeahead_type_basic"\x3e\n'+(null!=(g=f(k,"if").call(null!=c?c:e.nullContext||{},null!=c?f(c,"suggestions"):c,{name:"if",hash:{},fn:e.program(1,a,0),inverse:e.noop,data:a,loc:{start:{line:2,column:1},end:{line:12,column:8}}}))?g:"")+"\x3c/div\x3e"},useData:!0});this.Mathworks=this.Mathworks||{};this.Mathworks.templates=this.Mathworks.templates||{};
this.Mathworks.templates.searchgrouptypeaheadbs5=Handlebars.template({1:function(e,c,k,f,a,g,h){var d;f=e.lookupProperty||function(b,l){if(Object.prototype.hasOwnProperty.call(b,l))return b[l]};return null!=(d=f(k,"each").call(null!=c?c:e.nullContext||{},null!=c?f(c,"pages"):c,{name:"each",hash:{},fn:e.program(2,a,0,g,h),inverse:e.noop,data:a,loc:{start:{line:3,column:2},end:{line:37,column:11}}}))?d:""},2:function(e,c,k,f,a,g,h){var d;f=e.lookupProperty||function(b,l){if(Object.prototype.hasOwnProperty.call(b,
l))return b[l]};return null!=(d=f(k,"if").call(null!=c?c:e.nullContext||{},null!=c?f(c,"suggestions"):c,{name:"if",hash:{},fn:e.program(3,a,0,g,h),inverse:e.noop,data:a,loc:{start:{line:4,column:3},end:{line:36,column:10}}}))?d:""},3:function(e,c,k,f,a,g,h){var d,b;f=null!=c?c:e.nullContext||{};var l=e.hooks.helperMissing,n=e.escapeExpression,m=e.lookupProperty||function(p,q){if(Object.prototype.hasOwnProperty.call(p,q))return p[q]};return'\t\t\t\t\x3cdiv class\x3d"typeahead_group" role\x3d"group" aria-label\x3d"'+
n((b=null!=(b=m(k,"header")||(null!=c?m(c,"header"):c))?b:l,"function"===typeof b?b.call(f,{name:"header",hash:{},data:a,loc:{start:{line:5,column:58},end:{line:5,column:68}}}):b))+'"\x3e\n\t\t\t\t\t\x3cdiv class\x3d"typeahead_group_title"\x3e'+n((b=null!=(b=m(k,"header")||(null!=c?m(c,"header"):c))?b:l,"function"===typeof b?b.call(f,{name:"header",hash:{},data:a,loc:{start:{line:6,column:40},end:{line:6,column:50}}}):b))+"\n"+(null!=(d=(m(k,"ifIn")||c&&m(c,"ifIn")||l).call(f,"fcn",null!=c?m(c,"type"):
c,{name:"ifIn",hash:{},fn:e.program(4,a,0,g,h),inverse:e.noop,data:a,loc:{start:{line:7,column:6},end:{line:9,column:15}}}))?d:"")+(null!=(d=(m(k,"ifIn")||c&&m(c,"ifIn")||l).call(f,"blk",null!=c?m(c,"type"):c,{name:"ifIn",hash:{},fn:e.program(6,a,0,g,h),inverse:e.noop,data:a,loc:{start:{line:10,column:6},end:{line:12,column:15}}}))?d:"")+'\t\t\t\t\t\x3c/div\x3e\n\t\t\t\t\t\x3cdiv class\x3d"typeahead_group_result"\x3e\n\t\t\t\t\t\t\x3cul class\x3d"suggestionarea dropdown-menu show"\x3e\n'+(null!=(d=
m(k,"each").call(f,null!=c?m(c,"suggestions"):c,{name:"each",hash:{},fn:e.program(8,a,0,g,h),inverse:e.noop,data:a,loc:{start:{line:16,column:7},end:{line:32,column:16}}}))?d:"")+"\t\t\t\t\t\t\x3c/ul\x3e\n\t\t\t\t\t\x3c/div\x3e\n\t\t\t\t\x3c/div\x3e\n"},4:function(e,c,k,f,a){return'\t\t\t\t\t\t\t\x3cspan class\x3d"icon-function"\x3e\x3c/span\x3e\n'},6:function(e,c,k,f,a){return'\t\t\t\t\t\t\t\x3cspan class\x3d"icon-block"\x3e\x3c/span\x3e\n'},8:function(e,c,k,f,a,g,h){var d,b;f=null!=c?c:e.nullContext||
{};var l=e.hooks.helperMissing,n=e.escapeExpression,m=e.lookupProperty||function(p,q){if(Object.prototype.hasOwnProperty.call(p,q))return p[q]};return'\t\t\t\t\t\t\t\t\x3cli class\x3d"suggestion"\x3e\n\t\t\t\t\t\t\t\t\t\x3ca class\x3d"suggestion_item dropdown-item" id\x3d"'+n((b=null!=(b=m(k,"type")||(null!=c?m(c,"type"):c))?b:l,"function"===typeof b?b.call(f,{name:"type",hash:{},data:a,loc:{start:{line:18,column:54},end:{line:18,column:62}}}):b))+"_"+n((b=null!=(b=m(k,"index")||a&&m(a,"index"))?
b:l,"function"===typeof b?b.call(f,{name:"index",hash:{},data:a,loc:{start:{line:18,column:63},end:{line:18,column:73}}}):b))+'" role\x3d"option"\n'+(null!=(d=m(k,"if").call(f,null!=h[2]?m(h[2],"typeaheadRelease"):h[2],{name:"if",hash:{},fn:e.program(9,a,0,g,h),inverse:e.program(11,a,0,g,h),data:a,loc:{start:{line:19,column:10},end:{line:23,column:17}}}))?d:"")+'\x3e\n\t\t\t\t\t\t\t\t\t\t\x3cspan class\x3d"suggestion_summary refname"\x3e\n\t\t\t\t\t\t\t\t\t\t\t'+(null!=(d=m(k,"each").call(f,null!=
c?m(c,"title"):c,{name:"each",hash:{},fn:e.program(13,a,0,g,h),inverse:e.noop,data:a,loc:{start:{line:25,column:11},end:{line:25,column:161}}}))?d:"")+"\n\t\t\t\t\t\t\t\t\t\t\t-\n\t\t\t\t\t\t\t\t\t\t\t"+(null!=(d=m(k,"each").call(f,null!=c?m(c,"summary"):c,{name:"each",hash:{},fn:e.program(13,a,0,g,h),inverse:e.noop,data:a,loc:{start:{line:27,column:11},end:{line:27,column:163}}}))?d:"")+'\n\t\t\t\t\t\t\t\t\t\t\x3c/span\x3e\n\t\t\t\t\t\t\t\t\t\t\x3cspan class\x3d"suggestion_product"\x3e'+n((b=null!=
(b=m(k,"product")||(null!=c?m(c,"product"):c))?b:l,"function"===typeof b?b.call(f,{name:"product",hash:{},data:a,loc:{start:{line:29,column:43},end:{line:29,column:54}}}):b))+"\x3c/span\x3e\n\t\t\t\t\t\t\t\t\t\x3c/a\x3e\n\t\t\t\t\t\t\t\t\x3c/li\x3e\n"},9:function(e,c,k,f,a,g,h){var d;f=e.escapeExpression;g=e.lookupProperty||function(b,l){if(Object.prototype.hasOwnProperty.call(b,l))return b[l]};return'\t\t\t\t\t\t\t\t\t\t\thref\x3d"/help/releases/'+f(e.lambda(null!=h[2]?g(h[2],"typeaheadRelease"):
h[2],c))+"/"+f((d=null!=(d=g(k,"path")||(null!=c?g(c,"path"):c))?d:e.hooks.helperMissing,"function"===typeof d?d.call(null!=c?c:e.nullContext||{},{name:"path",hash:{},data:a,loc:{start:{line:20,column:59},end:{line:20,column:67}}}):d))+'"\n'},11:function(e,c,k,f,a){var g;f=e.lookupProperty||function(h,d){if(Object.prototype.hasOwnProperty.call(h,d))return h[d]};return'\t\t\t\t\t\t\t\t\t\t\thref\x3d"/help/'+e.escapeExpression((g=null!=(g=f(k,"path")||(null!=c?f(c,"path"):c))?g:e.hooks.helperMissing,
"function"===typeof g?g.call(null!=c?c:e.nullContext||{},{name:"path",hash:{},data:a,loc:{start:{line:22,column:23},end:{line:22,column:31}}}):g))+'"\n\t\t\t\t\t\t\t\t\t\t'},13:function(e,c,k,f,a){var g;f=null!=c?c:e.nullContext||{};var h=e.hooks.helperMissing,d=e.lookupProperty||function(b,l){if(Object.prototype.hasOwnProperty.call(b,l))return b[l]};return(null!=(g=(d(k,"ifCond")||c&&d(c,"ifCond")||h).call(f,a&&d(a,"index"),"\x3d\x3d","1",{name:"ifCond",hash:{},fn:e.program(14,a,0),inverse:e.noop,
data:a,loc:{start:{line:25,column:26},end:{line:25,column:99}}}))?g:"")+e.escapeExpression(e.lambda(c,c))+(null!=(g=(d(k,"ifCond")||c&&d(c,"ifCond")||h).call(f,a&&d(a,"index"),"\x3d\x3d","1",{name:"ifCond",hash:{},fn:e.program(16,a,0),inverse:e.noop,data:a,loc:{start:{line:25,column:107},end:{line:25,column:152}}}))?g:"")},14:function(e,c,k,f,a){return'\x3cspan class\x3d"suggestion_highlight"\x3e'},16:function(e,c,k,f,a){return"\x3c/span\x3e"},18:function(e,c,k,f,a,g,h){var d,b;f=null!=c?c:e.nullContext||
{};var l=e.hooks.helperMissing,n=e.escapeExpression,m=e.lookupProperty||function(p,q){if(Object.prototype.hasOwnProperty.call(p,q))return p[q]};return'\t\t\x3cdiv class\x3d"typeahead_group" role\x3d"group" aria-label\x3d"'+n((b=null!=(b=m(k,"labelSuggestions")||(null!=c?m(c,"labelSuggestions"):c))?b:l,"function"===typeof b?b.call(f,{name:"labelSuggestions",hash:{},data:a,loc:{start:{line:40,column:56},end:{line:40,column:76}}}):b))+'"\x3e\n\t\t\t\x3cdiv class\x3d"typeahead_group_title"\x3e'+n((b=
null!=(b=m(k,"labelSuggestions")||(null!=c?m(c,"labelSuggestions"):c))?b:l,"function"===typeof b?b.call(f,{name:"labelSuggestions",hash:{},data:a,loc:{start:{line:41,column:38},end:{line:41,column:58}}}):b))+'\x3c/div\x3e\n\t\t\t\x3cdiv class\x3d"typeahead_group_result"\x3e\n\t\t\t\t\x3cul class\x3d"suggestionarea dropdown-menu show"\x3e\n'+(null!=(d=m(k,"each").call(f,null!=(d=null!=c?m(c,"words"):c)?m(d,"wordlist"):d,{name:"each",hash:{},fn:e.program(19,a,0,g,h),inverse:e.noop,data:a,loc:{start:{line:44,
column:5},end:{line:52,column:14}}}))?d:"")+'\t\t\t\t\x3c/ul\x3e\n\t\t\t\x3c/div\x3e\n\t\t\x3c/div\x3e\n\t\t\x3cdiv class\x3d"text-center add_margin_20"\x3e\n\t\t\t\x3chr\x3e\n\t\t\t\x3ca href\x3d"/support/search.html?s_tid\x3dta_see_all_results\x26q\x3d'+n((b=null!=(b=m(k,"searchtext")||(null!=c?m(c,"searchtext"):c))?b:l,"function"===typeof b?b.call(f,{name:"searchtext",hash:{},data:a,loc:{start:{line:58,column:60},end:{line:58,column:74}}}):b))+'" tabindex\x3d"0" class\x3d"see_all_results"\x3e'+
n((b=null!=(b=m(k,"labelSeeAllResults")||(null!=c?m(c,"labelSeeAllResults"):c))?b:l,"function"===typeof b?b.call(f,{name:"labelSeeAllResults",hash:{},data:a,loc:{start:{line:58,column:113},end:{line:58,column:135}}}):b))+"\x3c/a\x3e\n\t\t\x3c/div\x3e\n"},19:function(e,c,k,f,a,g,h){var d,b;f=null!=c?c:e.nullContext||{};var l=e.hooks.helperMissing,n=e.escapeExpression,m=e.lookupProperty||function(p,q){if(Object.prototype.hasOwnProperty.call(p,q))return p[q]};return'\t\t\t\t\t\t\x3cli class\x3d"suggestion"\x3e\n\t\t\t\t\t\t\t\x3ca class\x3d"suggestion_item dropdown-item" id\x3d"suggestion_'+
n((b=null!=(b=m(k,"index")||a&&m(a,"index"))?b:l,"function"===typeof b?b.call(f,{name:"index",hash:{},data:a,loc:{start:{line:46,column:63},end:{line:46,column:73}}}):b))+'" role\x3d"option" href\x3d"/support/search.html?suggestion\x3dtrue\x26q\x3d'+n((b=null!=(b=m(k,"fullword")||(null!=c?m(c,"fullword"):c))?b:l,"function"===typeof b?b.call(f,{name:"fullword",hash:{},data:a,loc:{start:{line:46,column:134},end:{line:46,column:146}}}):b))+'"\x3e\n\t\t\t\t\t\t\t\t\x3cspan class\x3d"suggestion_summary"\x3e\n\t\t\t\t\t\t\t\t\t'+
(null!=(d=m(k,"each").call(f,null!=c?m(c,"splitwordlist"):c,{name:"each",hash:{},fn:e.program(13,a,0,g,h),inverse:e.noop,data:a,loc:{start:{line:48,column:9},end:{line:48,column:167}}}))?d:"")+"\n\t\t\t\t\t\t\t\t\x3c/span\x3e\n\t\t\t\t\t\t\t\x3c/a\x3e\n\t\t\t\t\t\t\x3c/li\x3e\n"},compiler:[8,"\x3e\x3d 4.3.0"],main:function(e,c,k,f,a,g,h){var d;f=null!=c?c:e.nullContext||{};var b=e.lookupProperty||function(l,n){if(Object.prototype.hasOwnProperty.call(l,n))return l[n]};return'\x3cdiv class\x3d"typeahead_container typeahead_type_grouped -presentation_grouped dropdown" id\x3d"search_suggestions" role\x3d"listbox"\x3e\n'+
(null!=(d=b(k,"if").call(f,null!=c?b(c,"pages"):c,{name:"if",hash:{},fn:e.program(1,a,0,g,h),inverse:e.noop,data:a,loc:{start:{line:2,column:1},end:{line:38,column:8}}}))?d:"")+(null!=(d=b(k,"if").call(f,null!=(d=null!=c?b(c,"words"):c)?b(d,"wordlist"):d,{name:"if",hash:{},fn:e.program(18,a,0,g,h),inverse:e.noop,data:a,loc:{start:{line:39,column:1},end:{line:60,column:8}}}))?d:"")+"\x3c/div\x3e"},useData:!0,useDepths:!0});
(function(){function e(c,k,f){function a(d,b){if(!k[d]){if(!c[d]){var l="function"==typeof require&&require;if(!b&&l)return l(d,!0);if(g)return g(d,!0);b=Error("Cannot find module '"+d+"'");throw b.code="MODULE_NOT_FOUND",b;}b=k[d]={exports:{}};c[d][0].call(b.exports,function(n){return a(c[d][1][n]||n)},b,b.exports,e,c,k,f)}return k[d].exports}for(var g="function"==typeof require&&require,h=0;h<f.length;h++)a(f[h]);return a}return e})()({1:[function(e,c,k){e=function(f,a){this.attributes=Object.assign({},
a);this.settings=Object.assign({},f)};Object.assign(e.prototype,{getSuggestion:function(f,a,g){var h=this;h.searchForm=a;h.searchQuery=g;if(f){f=f[0];var d=f.dataset.typeaheadType||"basic",b=f.dataset.typeaheadRelease;g=f.dataset.typeaheadProxyUrl+"/"+d+"?resources\x3d"+(f.dataset.typeaheadCollection||"latestdoc")+"\x26site_domain\x3d"+(f.dataset.siteDomain||"www")+"\x26site_language\x3d"+(f.dataset.siteLanguage||"en")+"\x26result_count\x3d"+(f.dataset.typeaheadResultCount||"10")+"\x26q\x3d"+g+"\x26format\x3ddoc";
b&&(g+="\x26release\x3d"+b);h.activeController&&h.activeController.abort();h.activeController=new AbortController;f=h.activeController.signal;h.searchQuery?fetch(g,{signal:f}).then(function(l){return l.json()}).then(function(l){l.status&&"200"!==l.status?console.error("Error fetching Typeahead results:",l.error):h.updateTypeaheadSuggestion(l,d,b)}).catch(function(l){"AbortError"!==l.name&&console.error("Error fetching JSON:",l)}):window.dispatchEvent(new CustomEvent("removedSuggestion"))}},updateTypeaheadSuggestion:function(f,
a,g){if("basic"===a&&0<(null==f?void 0:f.length)&&!f.error)this.suggestions=f,window.dispatchEvent(new CustomEvent("updatedBasicTypeaheadSuggestion",{detail:{model:this}}));else{var h,d,b;"grouped"===a&&((null==f?0:null==(h=f.pages)?0:h.some(function(l){return Array.isArray(l.suggestions)&&0<l.suggestions.length}))||0<(null==f?void 0:null==(d=f.words)?void 0:null==(b=d.wordlist)?void 0:b.length))?(this.searchtext=f.searchtext,this.pages=f.pages,this.words=f.words,this.typeaheadRelease=g,window.dispatchEvent(new CustomEvent("updatedGroupTypeaheadSuggestion",
{detail:{model:this}}))):window.dispatchEvent(new Event("removedSuggestion"))}}});c.exports=e},{}],2:[function(e,c,k){var f=e("./TypeaheadModel.js");e=function(a){this.settings=Object.assign({},a);this.el=this.settings.el;this.model=new f({url:this.el.getAttribute("data-url")});this.typeaheadType=(a=document.querySelectorAll(".conjoined_search")[0].getAttribute("data-typeahead-type"))?a:"basic";this.labelSuggestions=document.querySelectorAll(".form-control.conjoined_search")[0].getAttribute("data-label-suggestions");
this.labelSeeAllResults=document.querySelectorAll(".form-control.conjoined_search")[0].getAttribute("data-label-see-all-results");this.init()};Object.assign(e.prototype,{init:function(){var a=this;window.SearchTracking={};window.addEventListener("updatedBasicTypeaheadSuggestion",function(d){a.getSearchBasicTypeahead(d.detail.model)});window.addEventListener("updatedGroupTypeaheadSuggestion",function(d){a.getSearchGroupTypeahead(d.detail.model)});window.addEventListener("removedSuggestion",function(){a.removeSuggestions()});
a.el.addEventListener("keyup",function(d){d=d.keyCode?d.keyCode:d.charCode;40!==d&&38!==d&&27!==d&&13!==d&&a.updateTypeAhead()});a.el.addEventListener("keydown",function(d){var b=d.keyCode?d.keyCode:d.charCode;40===b||38===b?(d.preventDefault(),a.handleArrowKey(b),a.updateActiveDescendant()):27===b?(d.preventDefault(),a.removeSuggestions()):13===b&&a.handleEnterKey(d)});var g;null==(g=document.querySelectorAll("form"))||g.forEach(function(d){d.addEventListener("click",function(b){b.target.closest(".suggestion_item")&&
"basic"===a.typeaheadType&&(b.preventDefault(),b.target.closest("form").querySelector('input[type\x3d"search"]').value=b.target.closest(".suggestion_item").getAttribute("data-value"),b.target.closest("form").submit(),document.querySelector('input[type\x3d"search"]').value="");var l,n;"grouped"===a.typeaheadType&&b.target.closest(".suggestion_item")&&(null==(l=b.target)?0:null==(n=l.parentElement)?0:n.href)&&a.setTracking(b.target.parentElement.href);!b.target.closest(".typeahead_container")&&b.target.closest("button")&&
a.removeSuggestions()})});document.body.addEventListener("click",function(d){d.target.closest("#global_search_container")||d.target.closest("#inpage_search_container")||a.removeSuggestions()});window.addEventListener("resize",function(){a.updateContainerWidth()});window.addEventListener("orientationchange",function(){a.updateContainerWidth()});var h;null==(h=document.querySelectorAll(".conjoined_search"))||h.forEach(function(d){d.addEventListener("input",function(){""===a.el.value&&a.removeSuggestions()})})},
updateTypeAhead:function(){var a=this.model,g=this.el.value,h=this.el.closest("form"),d,b=document.querySelectorAll("input[data-typeahead-collection]");0!==b.length&&(d=b);a.getSuggestion(d,h,g)},updateContainerHeight:function(){var a=document.querySelector(".typeahead_container");if(a){var g=a.getBoundingClientRect().top;a.style.maxHeight="calc(99dvh - "+g+"px)"}},updateContainerWidth:function(){var a=this.el.closest("form"),g="basic"===this.typeaheadType?document.querySelector(".typeahead_type_basic"):
document.querySelector(".typeahead_type_grouped");if(g){var h=a.offsetWidth;"grouped"===this.typeaheadType&&("767"<window.innerWidth&&(h+=100),100>a.offsetLeft&&(g.style.marginLeft="0",h-=a.offsetLeft));g.style.width=h+"px"}},removeSuggestions:function(){var a=document.querySelector(".typeahead_container");a&&a.remove();(a=document.querySelector(".input-group.active_typeahead"))&&a.classList.remove("active_typeahead");this.hideModal()},getSearchBasicTypeahead:function(a){if(""!==a.searchForm.value){var g=
a.searchForm.querySelector(".input-group"),h;0<(null==(h=a.suggestions)?void 0:h.length)&&(h=Mathworks.templates.searchbasictypeahead({suggestions:a.suggestions,qvalue:a.searchForm.value}),a.searchForm.parentElement.classList.add("active_typeahead"),this.displayModal(),(a=document.querySelector(".typeahead_type_basic"))?a.outerHTML=h:g.insertAdjacentHTML("beforeend",h));this.updateContainerHeight();this.updateContainerWidth()}else this.removeSuggestions()},getSearchGroupTypeahead:function(a){if(""!==
a.searchForm.value){var g=a.words.wordlist,h=a.pages,d=a.searchForm.querySelector(".input-group");if(0<(null==g?void 0:g.length)||(null==h?0:h.some(function(b){return Array.isArray(b.suggestions)&&0<b.suggestions.length})))g=Mathworks.templates.searchgrouptypeaheadbs5({pages:a.pages,words:a.words,searchtext:a.searchtext,typeaheadRelease:a.typeaheadRelease,labelSeeAllResults:this.labelSeeAllResults,labelSuggestions:this.labelSuggestions}),a.searchForm.parentElement.classList.add("active_typeahead"),
this.displayModal(),(a=document.querySelector(".typeahead_type_grouped"))?a.outerHTML=g:d.insertAdjacentHTML("beforeend",g);this.updateContainerHeight();this.updateContainerWidth()}else this.removeSuggestions()},displayModal:function(){var a=document.getElementById("typeahead_modal");a||(a=document.createElement("div"),a.id="typeahead_modal",document.body.appendChild(a));a&&!a.classList.contains("in")&&(a.classList.add("in"),document.body.classList.add("typeahead_modal"))},hideModal:function(){document.body.classList.remove("typeahead_modal");
var a=document.getElementById("typeahead_modal");a&&(a.style.display="none")},handleArrowKey:function(a){var g=document.querySelector(".selected-suggestion"),h=document.querySelectorAll(".suggestionarea");if(g){var d=g.closest(".suggestionarea");if(40===a||38===a){if(40===a){for(a=g.nextElementSibling;a&&!a.classList.contains("suggestion");)a=a.nextElementSibling;if(!a){var b=d.parentElement.parentElement.nextElementSibling;b&&(b=b.querySelector(".suggestionarea .suggestion"))&&(a=b)}}else{for(a=
g.previousElementSibling;a&&!a.classList.contains("suggestion");)a=a.previousElementSibling;!a&&(b=d.parentElement.parentElement.previousElementSibling)&&(b=b.querySelectorAll(".suggestionarea .suggestion"),0<b.length&&(a=b[b.length-1]))}g.classList.remove("selected-suggestion");a&&a.classList.add("selected-suggestion")}d&&(g=document.querySelector(".selected-suggestion"))&&(d.scrollTop+=g.getBoundingClientRect().top-d.getBoundingClientRect().top)}else 40===a?(g=null==(d=h[0])?void 0:d.querySelector(".suggestion"))&&
g.classList.add("selected-suggestion"):38===a&&(g=null==(b=h[h.length-1])?void 0:b.querySelectorAll(".suggestion"))&&0<g.length&&g[g.length-1].classList.add("selected-suggestion")},handleEnterKey:function(a){var g=document.querySelector(".selected-suggestion");"basic"===this.typeaheadType?g&&(a.preventDefault(),a.target.closest("form").querySelector('input[type\x3d"search"]').value=g.querySelector("a").getAttribute("data-value"),a.target.closest("form").submit(),this.removeSuggestions(),document.querySelector('input[type\x3d"search"]').value=
""):(g?(a.preventDefault(),a=g.querySelector("a").getAttribute("href")):a="/support/search.html?q\x3d"+this.el.value,a&&(window.location=a,this.setTracking(a)))},setTracking:function(a){0!==a.length&&(SearchTracking.app="support_results",-1<a.indexOf("/support/search.html?suggestion\x3dtrue\x26q\x3d")?(a=a.substring(a.lastIndexOf("q\x3d")+2),SearchTracking.typeahead=a,SearchTracking.term=a,SearchTracking.page=1):(SearchTracking.typeahead=a,SearchTracking.term=a,SearchTracking.page="direct","undefined"!==
typeof _satellite&&_satellite.track("cruxTypeAhead")))},updateActiveDescendant:function(){var a,g=null==(a=document.querySelectorAll(".selected-suggestion .suggestion_item")[0])?void 0:a.id;a=document.querySelector("#query");g&&a&&a.setAttribute("aria-activedescendant",g)}});c.exports=e},{"./TypeaheadModel.js":1}],3:[function(e,c,k){var f=e("./TypeaheadView.js");document.addEventListener("DOMContentLoaded",function(){document.querySelectorAll(".form-control.conjoined_search").forEach(function(a){new f({el:a})})})},
{"./TypeaheadView.js":2}]},{},[3]);