(function(){function D(z,A,n){function m(h,r){if(!A[h]){if(!z[h]){var E="function"==typeof require&&require;if(!r&&E)return E(h,!0);if(a)return a(h,!0);r=Error("Cannot find module '"+h+"'");throw r.code="MODULE_NOT_FOUND",r;}r=A[h]={exports:{}};z[h][0].call(r.exports,function(w){return m(z[h][1][w]||w)},r,r.exports,D,z,A,n)}return A[h].exports}for(var a="function"==typeof require&&require,e=0;e<n.length;e++)m(n[e]);return m}return D})()({1:[function(D,z,A){var n=D("web-vitals");window.webVitalsData=
{};var m={init:function(){var a=this;n.onCLS(a.addCLSToQueue);n.onLCP(a.addLCPToQueue);n.onFCP(a.addFCPToQueue);n.onTTFB(a.addTTFBToQueue);n.onINP(a.addINPToQueue);addEventListener("error",function(e){a.handleJSError(a,e)});addEventListener("visibilitychange",function(){"hidden"===document.visibilityState&&m.sendPerformanceData()});addEventListener("pagehide",function(){m.sendPerformanceData()})},addCLSToQueue:function(a){window.webVitalsData.cls=a.value.toFixed(3);if(0<a.value){a=a.entries.reduce(function(h,
r){return h.value>r.value?h:r});var e;0<(null==(e=a.sources)?void 0:e.length)&&(window.webVitalsData.clsSource=m.htmlElementToString(a.sources[0].node),window.webVitalsData.clsSourceTree=m.htmlElementToAncestorString(a.sources[0].node))}},addLCPToQueue:function(a){window.webVitalsData.lcp=Math.round(a.value);a.entries.length&&(a=a.entries[a.entries.length-1],window.webVitalsData.lcpUrl=a.url,window.webVitalsData.lcpTarget=m.htmlElementToString(a.element),window.webVitalsData.lcpTargetTree=m.htmlElementToAncestorString(a.element))},
addFCPToQueue:function(a){window.webVitalsData.fcp=Math.round(a.value)},addTTFBToQueue:function(a){window.webVitalsData.ttfb=Math.round(a.value);0<a.entries.length&&(window.webVitalsData.domComplete=Math.round(a.entries[0].domComplete),window.webVitalsData.domInteractive=Math.round(a.entries[0].domInteractive),window.webVitalsData.entryType=a.entries[0].entryType)},addINPToQueue:function(a){window.webVitalsData.inp=a.value;a.entries.length&&(a=a.entries.reduce(function(e,h){return e.target&&h.target||
!e.target&&!h.target?e.duration>h.duration?e:h:e.target?e:h},{duration:0}),window.webVitalsData.inpName=a.name,window.webVitalsData.inpDuration=a.duration,a.target&&(window.webVitalsData.inpTarget=m.htmlElementToString(a.target),window.webVitalsData.inpTargetTree=m.htmlElementToAncestorString(a.target)))},htmlElementToString:function(a){if(a){var e=a.localName;a.id&&0<a.id.length&&(e+="#"+a.id);a.className&&0<a.className.length&&(e+="."+a.className.trim().replaceAll(/\s+/g,"."));return e}return""},
htmlElementToAncestorString:function(a){for(var e="",h;a&&"body"!==(null==(h=a)?void 0:h.localName);)e&&(e=" \x3e "+e),e=m.htmlElementToString(a)+e,a=a.parentElement;return e},generateSessionKey:function(){"undefined"===typeof sessionStorage.cwvSessionId&&(sessionStorage.cwvSessionId="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var e=16*Math.random()|0;return("x"===a?e:e&3|8).toString(16)}));return sessionStorage.cwvSessionId},flushData:function(){window.webVitalsData={}},sendPerformanceData:function(){Object.keys(window.webVitalsData).length&&
!location.hostname.includes("aem")&&(m.sendData(window.webVitalsData,"web vitals"),m.flushData())},handleJSError:function(a,e){var h={};h.errorMessage=e.message;e.error&&(h.errorName=e.error.name);try{h.errorFilename=e.filename,h.lineNumber=e.lineno,h.columnNumber=e.colno,e.error&&(h.errorStack=e.error.stack,h.errorMessage=e.error.message)}catch(r){}a.sendData(h,"javascript")},sendData:function(a,e){var h="WEB_CORE_WEB_VITALS";"javascript"===e&&(h="JS_ERRORS");a.country=window.MathWorksCountryCode;
a.region=window.MathWorksRegionCode;a.userAgent=navigator.userAgent;a.query=location.search;a.host=location.host;a.pathname=location.pathname;"undefined"!==typeof _satellite&&(a.sessionid=_satellite.getVisitorId().getMarketingCloudVisitorID());e="https://udc-service.mathworks.com/udc/service/v1/events";location.hostname.includes("-")&&(e="https://udc-service-integ3.mathworks.com/udc/service/v1/events");fetch(e,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json","x-mw-udc-client-version":"1.0",
"x-mw-udc-application-name":"WEB_PAGE_METRICS","x-mw-udc-application-version":"0.5","x-mw-authentication":"2369b91c-a64f-11ec-b909-0242ac120002"},cache:"no-cache",keepalive:!0,body:JSON.stringify({Event:[{sessionKey:this.generateSessionKey(),eventKey:h,eventDate:(new Date).toISOString().slice(0,23),eventData:JSON.stringify(a)}]})})}};z.exports=m;m.init()},{"web-vitals":2}],2:[function(D,z,A){!function(n,m){"object"==typeof A&&"undefined"!=typeof z?m(A):"function"==typeof define&&define.amd?define(["exports"],
m):m((n="undefined"!=typeof globalThis?globalThis:n||self).webVitals={})}(this,function(n){var m,a,e,h,r,E=-1,w=function(d){addEventListener("pageshow",function(b){b.persisted&&(E=b.timeStamp,d(b))},!0)},N=function(){var d=self.performance&&performance.getEntriesByType&&performance.getEntriesByType("navigation")[0];if(d&&0<d.responseStart&&d.responseStart<performance.now())return d},I=function(){var d=N();return d&&d.activationStart||0},t=function(d,b){var c=N(),g="navigate";0<=E?g="back-forward-cache":
c&&(document.prerendering||0<I()?g="prerender":document.wasDiscarded?g="restore":c.type&&(g=c.type.replace(/_/g,"-")));return{name:d,value:void 0===b?-1:b,rating:"good",delta:0,entries:[],id:"v4-".concat(Date.now(),"-").concat(Math.floor(8999999999999*Math.random())+1E12),navigationType:g}},B=function(d,b,c){try{if(PerformanceObserver.supportedEntryTypes.includes(d)){var g=new PerformanceObserver(function(f){Promise.resolve().then(function(){b(f.getEntries())})});return g.observe(Object.assign({type:d,
buffered:!0},c||{})),g}}catch(f){}},u=function(d,b,c,g){var f,l;return function(k){0<=b.value&&(k||g)&&((l=b.value-(f||0))||void 0===f)&&(f=b.value,b.delta=l,k=b.value,b.rating=k>c[1]?"poor":k>c[0]?"needs-improvement":"good",d(b))}},O=function(d){requestAnimationFrame(function(){return requestAnimationFrame(function(){return d()})})},F=function(d){document.addEventListener("visibilitychange",function(){"hidden"===document.visibilityState&&d()})},J=function(d){var b=!1;return function(){b||(d(),b=
!0)}},C=-1,K=function(d){"hidden"===document.visibilityState&&-1<C&&(C="visibilitychange"===d.type?d.timeStamp:0,removeEventListener("visibilitychange",K,!0),removeEventListener("prerenderingchange",K,!0))},Z=function(){addEventListener("visibilitychange",K,!0);addEventListener("prerenderingchange",K,!0)},P=function(){return 0>C&&(C="hidden"!==document.visibilityState||document.prerendering?1/0:0,Z(),w(function(){setTimeout(function(){C="hidden"!==document.visibilityState||document.prerendering?1/
0:0;Z()},0)})),{get firstHiddenTime(){return C}}},G=function(d){document.prerendering?addEventListener("prerenderingchange",function(){return d()},!0):d()},Q=[1800,3E3],aa=function(d,b){b=b||{};G(function(){var c,g=P(),f=t("FCP"),l=B("paint",function(k){k.forEach(function(p){"first-contentful-paint"===p.name&&(l.disconnect(),p.startTime<g.firstHiddenTime&&(f.value=Math.max(p.startTime-I(),0),f.entries.push(p),c(!0)))})});l&&(c=u(d,f,Q,b.reportAllChanges),w(function(k){f=t("FCP");c=u(d,f,Q,b.reportAllChanges);
O(function(){f.value=performance.now()-k.timeStamp;c(!0)})}))})},R=[.1,.25],S=0,T=1/0,L=0,ha=function(d){d.forEach(function(b){b.interactionId&&(T=Math.min(T,b.interactionId),L=Math.max(L,b.interactionId),S=L?(L-T)/7+1:0)})},x=[],M=new Map,ba=0,ia=[],ja=function(d){if(ia.forEach(function(g){return g(d)}),d.interactionId||"first-input"===d.entryType){var b=x[x.length-1],c=M.get(d.interactionId);if(c||10>x.length||d.duration>b.latency)c?d.duration>c.latency?(c.entries=[d],c.latency=d.duration):d.duration===
c.latency&&d.startTime===c.entries[0].startTime&&c.entries.push(d):(b={id:d.interactionId,latency:d.duration,entries:[d]},M.set(b.id,b),x.push(b)),x.sort(function(g,f){return f.latency-g.latency}),10<x.length&&x.splice(10).forEach(function(g){return M.delete(g.id)})}},ca=function(d){var b=self.requestIdleCallback||self.setTimeout,c=-1;return d=J(d),"hidden"===document.visibilityState?d():(c=b(d),F(d)),c},U=[200,500],V=[2500,4E3],W={},X=[800,1800],ka=function c(b){document.prerendering?G(function(){return c(b)}):
"complete"!==document.readyState?addEventListener("load",function(){return c(b)},!0):setTimeout(b,0)},H={passive:!0,capture:!0},la=new Date,fa=function(b,c){a||(a=c,e=b,h=new Date,da(removeEventListener),ea())},ea=function(){if(0<=e&&e<h-la){var b={entryType:"first-input",name:a.type,target:a.target,cancelable:a.cancelable,startTime:a.timeStamp,processingStart:a.timeStamp+e};r.forEach(function(c){c(b)});r=[]}},ma=function(b){if(b.cancelable){var c=(1E12<b.timeStamp?new Date:performance.now())-b.timeStamp;
"pointerdown"==b.type?function(g,f){var l=function(){fa(g,f);p()},k=function(){p()},p=function(){removeEventListener("pointerup",l,H);removeEventListener("pointercancel",k,H)};addEventListener("pointerup",l,H);addEventListener("pointercancel",k,H)}(c,b):fa(c,b)}},da=function(b){["mousedown","keydown","touchstart","pointerdown"].forEach(function(c){return b(c,ma,H)})},Y=[100,300];n.CLSThresholds=R;n.FCPThresholds=Q;n.FIDThresholds=Y;n.INPThresholds=U;n.LCPThresholds=V;n.TTFBThresholds=X;n.onCLS=function(b,
c){c=c||{};aa(J(function(){var g,f=t("CLS",0),l=0,k=[],p=function(q){q.forEach(function(v){if(!v.hadRecentInput){var na=k[0],oa=k[k.length-1];l&&1E3>v.startTime-oa.startTime&&5E3>v.startTime-na.startTime?(l+=v.value,k.push(v)):(l=v.value,k=[v])}});l>f.value&&(f.value=l,f.entries=k,g())},y=B("layout-shift",p);y&&(g=u(b,f,R,c.reportAllChanges),F(function(){p(y.takeRecords());g(!0)}),w(function(){l=0;f=t("CLS",0);g=u(b,f,R,c.reportAllChanges);O(function(){return g()})}),setTimeout(g,0))}))};n.onFCP=
aa;n.onFID=function(b,c){c=c||{};G(function(){var g=P(),f=t("FID"),l=function(q){q.startTime<g.firstHiddenTime&&(f.value=q.processingStart-q.startTime,f.entries.push(q),y(!0))},k=function(q){q.forEach(l)},p=B("first-input",k);var y=u(b,f,Y,c.reportAllChanges);p&&(F(J(function(){k(p.takeRecords());p.disconnect()})),w(function(){f=t("FID");y=u(b,f,Y,c.reportAllChanges);r=[];e=-1;a=null;da(addEventListener);r.push(l);ea()}))})};n.onINP=function(b,c){"PerformanceEventTiming"in self&&"interactionId"in
PerformanceEventTiming.prototype&&(c=c||{},G(function(){var g;"interactionCount"in performance||m||(m=B("event",ha,{type:"event",buffered:!0,durationThreshold:0}));var f=t("INP"),l=function(y){ca(function(){y.forEach(ja);var q;(q=x[Math.min(x.length-1,Math.floor(((m?S:performance.interactionCount||0)-ba)/50))])&&q.latency!==f.value&&(f.value=q.latency,f.entries=q.entries,p())})},k=B("event",l,{durationThreshold:null!==(g=c.durationThreshold)&&void 0!==g?g:40});var p=u(b,f,U,c.reportAllChanges);k&&
(k.observe({type:"first-input",buffered:!0}),F(function(){l(k.takeRecords());p(!0)}),w(function(){ba=m?S:performance.interactionCount||0;x.length=0;M.clear();f=t("INP");p=u(b,f,U,c.reportAllChanges)}))}))};n.onLCP=function(b,c){c=c||{};G(function(){var g=P(),f=t("LCP"),l=function(q){c.reportAllChanges||(q=q.slice(-1));q.forEach(function(v){v.startTime<g.firstHiddenTime&&(f.value=Math.max(v.startTime-I(),0),f.entries=[v],p())})},k=B("largest-contentful-paint",l);if(k){var p=u(b,f,V,c.reportAllChanges);
var y=J(function(){W[f.id]||(l(k.takeRecords()),k.disconnect(),W[f.id]=!0,p(!0))});["keydown","click"].forEach(function(q){addEventListener(q,function(){return ca(y)},{once:!0,capture:!0})});F(y);w(function(q){f=t("LCP");p=u(b,f,V,c.reportAllChanges);O(function(){f.value=performance.now()-q.timeStamp;W[f.id]=!0;p(!0)})})}})};n.onTTFB=function(b,c){c=c||{};var g=t("TTFB"),f=u(b,g,X,c.reportAllChanges);ka(function(){var l=N();l&&(g.value=Math.max(l.responseStart-I(),0),g.entries=[l],f(!0),w(function(){g=
t("TTFB",0);(f=u(b,g,X,c.reportAllChanges))(!0)}))})}})},{}]},{},[1]);